import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
import { z } from "zod";

extendZodWithOpenApi(z);

export const AttributeResponseSchema = z.object({
  "Harvested acres": z.number().openapi({ description: "Total harvested acres" }).optional(),
  "Planted acres": z.number().openapi({ description: "Total planted acres" }).optional(),
  "Per capita disappearance": z.number().openapi({ description: "Per capita disappearance of commodities" }).optional(),
  Beef: z.number().openapi({ description: "Amount of Beef" }).optional(),
  Broilers: z.number().openapi({ description: "Amount of Broilers" }).optional(),
  "Lamb & mutton": z.number().openapi({ description: "Amount of Lamb & Mutton" }).optional(),
  "Total red meat": z.number().openapi({ description: "Total red meat produced" }).optional(),
  "Other chicken": z.number().openapi({ description: "Amount of Other Chicken" }).optional(),
  Pork: z.number().openapi({ description: "Amount of Pork" }).optional(),
  Turkeys: z.number().openapi({ description: "Amount of Turkeys" }).optional(),
  Veal: z.number().openapi({ description: "Amount of Veal" }).optional(),
  "Total poultry": z.number().openapi({ description: "Total poultry production" }).optional(),
  "Red meat & poultry": z.number().openapi({ description: "Combined total of red meat & poultry" }).optional(),
  "Beginning stocks": z.number().openapi({ description: "Beginning stocks of commodities" }).optional(),
  "Ending stocks": z.number().openapi({ description: "Ending stocks of commodities" }).optional(),
  Imports: z.number().openapi({ description: "Imports of commodities" }).optional(),
  Production: z.number().openapi({ description: "Total production of commodities" }).optional(),
  "Total supply": z.number().openapi({ description: "Total supply of commodities" }).optional(),
  "Domestic use": z.number().openapi({ description: "Domestic use of commodities" }).optional(),
  "Ethanol and by-products": z.number().openapi({ description: "Ethanol and by-products produced" }).optional(),
  "Food, seed, & industrial": z.number().openapi({ description: "Food, seed, & industrial usage" }).optional(),
  Food: z.number().openapi({ description: "Amount of Food" }).optional(),
  "Feed & residual": z.number().openapi({ description: "Feed & residual amount" }).optional(),
  Crush: z.number().openapi({ description: "Crush amount" }).optional(),
  Seed: z.number().openapi({ description: "Seed amount" }).optional(),
  "Seed and residual": z.number().openapi({ description: "Seed and residual amount" }).optional(),
  "Total use": z.number().openapi({ description: "Total usage of commodities" }).optional(),
  Exports: z.number().openapi({ description: "Exports of commodities" }).optional(),
  "Beef cow inventory": z.number().openapi({ description: "Beef cow inventory count" }).optional(),
  "Cattle inventory": z.number().openapi({ description: "Cattle inventory count" }).optional(),
  "Total cow inventory": z.number().openapi({ description: "Total cow inventory count" }).optional(),
  "Hog inventory Dec. 1, previous year": z.number().openapi({ description: "Hog inventory from previous year" }).optional(),
  "Number of cows": z.number().openapi({ description: "Total number of cows" }).optional(),
  Disappearance: z.number().openapi({ description: "Total disappearance of commodities" }).optional(),
  "Hatching use": z.number().openapi({ description: "Hatching use of commodities" }).optional(),
  "Net returns": z.number().openapi({ description: "Net returns from commodities" }).optional(),
  "Loan rate": z.number().openapi({ description: "Loan rate for production" }).optional(),
  "Crush margin (dollar/bushel)": z.number().openapi({ description: "Crush margin in dollars per bushel" }).optional(),
  "Farm price": z.number().openapi({ description: "Farm price of commodities" }).optional(),
  "National composite price": z.number().openapi({ description: "National composite price of commodities" }).optional(),
  "Broilers, farm price": z.number().openapi({ description: "Farm price of Broilers" }).optional(),
  "Turkey, farm price": z.number().openapi({ description: "Farm price of Turkey" }).optional(),
  "Hen turkeys, National price": z.number().openapi({ description: "National price for Hen Turkeys" }).optional(),
  "Stocks/use ratio, percent": z.number().openapi({ description: "Stocks to use ratio percentage" }).optional(),
  "Soybean oil price (dollar/pound)": z.number().openapi({ description: "Soybean oil price in dollars per pound" }).optional(),
  "Soybean meal price (dollar/ton)": z.number().openapi({ description: "Soybean meal price in dollars per ton" }).optional(),
  "All milk price": z.number().openapi({ description: "Price of all milk" }).optional(),
  "Steers, 5-area price": z.number().openapi({ description: "5-area price for Steers" }).optional(),
  "Beef cattle, farm price": z.number().openapi({ description: "Farm price for Beef cattle" }).optional(),
  "Calves, farm price": z.number().openapi({ description: "Farm price for Calves" }).optional(),
  "Hogs, farm price": z.number().openapi({ description: "Farm price for Hogs" }).optional(),
  "National base, live equivalent price": z.number().openapi({ description: "National base live equivalent price" }).optional(),
  "Feeder steers, Oklahoma City price": z.number().openapi({ description: "Price for Feeder steers in Oklahoma City" }).optional(),
  "Eggs, farm price": z.number().openapi({ description: "Farm price for Eggs" }).optional(),
  "New York, Grade A large price": z.number().openapi({ description: "Price for New York Grade A large eggs" }).optional(),
  "Crushing yields, soybean meal": z.number().openapi({ description: "Crushing yields for soybean meal" }).optional(),
  "Crushing yields, soybean oil": z.number().openapi({ description: "Crushing yields for soybean oil" }).optional(),
  "Variable cost of production (per acre)": z.number().openapi({ description: "Variable cost of production per acre" }).optional(),
  "Variable cost of production (per bushel)": z.number().openapi({ description: "Variable cost of production per bushel" }).optional(),
  "Variable cost of production (per pound)": z.number().openapi({ description: "Variable cost of production per pound" }).optional(),
  "Variable cost of production (per hundredweight)": z.number().openapi({ description: "Variable cost of production per hundredweight" }).optional(),
  "Milling rate, percent": z.number().openapi({ description: "Milling rate percentage" }).optional(),
  "Domestic use & residual": z.number().openapi({ description: "Domestic use and residual" }).optional(),
  "Milk per cow": z.number().openapi({ description: "Milk produced per cow" }).optional(),
  "Milk production": z.number().openapi({ description: "Total milk production" }).optional(),
  "Commercial use: Milkfat basis": z.number().openapi({ description: "Commercial use on a milkfat basis" }).optional(),
  "Commercial use: Skim solids": z.number().openapi({ description: "Commercial use on skim solids basis" }).optional(),
  "Federally inspected slaughter": z.number().openapi({ description: "Total federally inspected slaughter" }).optional(),
  "Commercial production": z.number().openapi({ description: "Commercial production total" }).optional(),
  "Farm production": z.number().openapi({ description: "Total farm production" }).optional(),
  "Total production": z.number().openapi({ description: "Total production of commodities" }).optional(),
  "Total disappearance": z.number().openapi({ description: "Total disappearance of commodities" }).optional(),
  "Soybean oil, for methyl ester": z.number().openapi({ description: "Soybean oil used for methyl ester" }).optional(),
  "Yield (bushel/harvested acre)": z.number().openapi({ description: "Yield in bushels per harvested acre" }).optional(),
  "Yield (pounds/harvested acre)": z.number().openapi({ description: "Yield in pounds per harvested acre" }).optional(),
}).openapi({
  title: "Attribute Histogram Response",
  description: "Response containing various attribute data metrics",
});

export type AttributeHistogramResponse = z.infer<typeof AttributeResponseSchema>;