import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
import { z } from "zod";

extendZodWithOpenApi(z);

export const AttributeResponseSchema = z.object({
  "Harvested acres": z.number().openapi({ description: "Total harvested acres" }),
  "Planted acres": z.number().openapi({ description: "Total planted acres" }),
  "Per capita disappearance": z.number().openapi({ description: "Per capita disappearance of commodities" }),
  Beef: z.number().openapi({ description: "Amount of Beef" }),
  Broilers: z.number().openapi({ description: "Amount of Broilers" }),
  "Lamb & mutton": z.number().openapi({ description: "Amount of Lamb & Mutton" }),
  "Total red meat": z.number().openapi({ description: "Total red meat produced" }),
  "Other chicken": z.number().openapi({ description: "Amount of Other Chicken" }),
  Pork: z.number().openapi({ description: "Amount of Pork" }),
  Turkeys: z.number().openapi({ description: "Amount of Turkeys" }),
  Veal: z.number().openapi({ description: "Amount of Veal" }),
  "Total poultry": z.number().openapi({ description: "Total poultry production" }),
  "Red meat & poultry": z.number().openapi({ description: "Combined total of red meat & poultry" }),
  "Beginning stocks": z.number().openapi({ description: "Beginning stocks of commodities" }),
  "Ending stocks": z.number().openapi({ description: "Ending stocks of commodities" }),
  "Ending Stocks": z.number().openapi({ description: "Ending Stocks (duplicate key)" }), // Note: Duplicate key
  Imports: z.number().openapi({ description: "Imports of commodities" }),
  Production: z.number().openapi({ description: "Total production of commodities" }),
  "Total supply": z.number().openapi({ description: "Total supply of commodities" }),
  "Domestic use": z.number().openapi({ description: "Domestic use of commodities" }),
  "Ethanol and by-products": z.number().openapi({ description: "Ethanol and by-products produced" }),
  "Food, seed, & industrial": z.number().openapi({ description: "Food, seed, & industrial usage" }),
  Food: z.number().openapi({ description: "Amount of Food" }),
  "Feed & residual": z.number().openapi({ description: "Feed & residual amount" }),
  Crush: z.number().openapi({ description: "Crush amount" }),
  Seed: z.number().openapi({ description: "Seed amount" }),
  "Seed and residual": z.number().openapi({ description: "Seed and residual amount" }),
  "Total use": z.number().openapi({ description: "Total usage of commodities" }),
  Exports: z.number().openapi({ description: "Exports of commodities" }),
  "Beef cow inventory": z.number().openapi({ description: "Beef cow inventory count" }),
  "Cattle inventory": z.number().openapi({ description: "Cattle inventory count" }),
  "Total cow inventory": z.number().openapi({ description: "Total cow inventory count" }),
  "Hog inventory Dec. 1, previous year": z.number().openapi({ description: "Hog inventory from previous year" }),
  "Number of cows": z.number().openapi({ description: "Total number of cows" }),
  Disappearance: z.number().openapi({ description: "Total disappearance of commodities" }),
  "Hatching use": z.number().openapi({ description: "Hatching use of commodities" }),
  "Net returns": z.number().openapi({ description: "Net returns from commodities" }),
  "Loan rate": z.number().openapi({ description: "Loan rate for production" }),
  "Crush margin (dollar/bushel)": z.number().openapi({ description: "Crush margin in dollars per bushel" }),
  "Farm price": z.number().openapi({ description: "Farm price of commodities" }),
  "National composite price": z.number().openapi({ description: "National composite price of commodities" }),
  "Broilers, farm price": z.number().openapi({ description: "Farm price of Broilers" }),
  "Turkey, farm price": z.number().openapi({ description: "Farm price of Turkey" }),
  "Hen turkeys, National price": z.number().openapi({ description: "National price for Hen Turkeys" }),
  "Stocks/use ratio, percent": z.number().openapi({ description: "Stocks to use ratio percentage" }),
  "Soybean oil price (dollar/pound)": z.number().openapi({ description: "Soybean oil price in dollars per pound" }),
  "Soybean meal price (dollar/ton)": z.number().openapi({ description: "Soybean meal price in dollars per ton" }),
  "All milk price": z.number().openapi({ description: "Price of all milk" }),
  "Steers, 5-area price": z.number().openapi({ description: "5-area price for Steers" }),
  "Beef cattle, farm price": z.number().openapi({ description: "Farm price for Beef cattle" }),
  "Calves, farm price": z.number().openapi({ description: "Farm price for Calves" }),
  "Hogs, farm price": z.number().openapi({ description: "Farm price for Hogs" }),
  "National base, live equivalent price": z.number().openapi({ description: "National base live equivalent price" }),
  "Feeder steers, Oklahoma City price": z.number().openapi({ description: "Price for Feeder steers in Oklahoma City" }),
  "Eggs, farm price": z.number().openapi({ description: "Farm price for Eggs" }),
  "New York, Grade A large price": z.number().openapi({ description: "Price for New York Grade A large eggs" }),
  "Crushing yields, soybean meal": z.number().openapi({ description: "Crushing yields for soybean meal" }),
  "Crushing yields, soybean oil": z.number().openapi({ description: "Crushing yields for soybean oil" }),
  "Variable cost of production (per acre)": z.number().openapi({ description: "Variable cost of production per acre" }),
  "Variable cost of production (per bushel)": z.number().openapi({ description: "Variable cost of production per bushel" }),
  "Variable cost of production (per pound)": z.number().openapi({ description: "Variable cost of production per pound" }),
  "Variable cost of production (per hundredweight)": z.number().openapi({ description: "Variable cost of production per hundredweight" }),
  "Milling rate, percent": z.number().openapi({ description: "Milling rate percentage" }),
  "Domestic use & residual": z.number().openapi({ description: "Domestic use and residual" }),
  "Milk per cow": z.number().openapi({ description: "Milk produced per cow" }),
  "Milk production": z.number().openapi({ description: "Total milk production" }),
  "Commercial use: Milkfat basis": z.number().openapi({ description: "Commercial use on a milkfat basis" }),
  "Commercial use: Skim solids": z.number().openapi({ description: "Commercial use on skim solids basis" }),
  "Federally inspected slaughter": z.number().openapi({ description: "Total federally inspected slaughter" }),
  "Commercial production": z.number().openapi({ description: "Commercial production total" }),
  "Farm production": z.number().openapi({ description: "Total farm production" }),
  "Total production": z.number().openapi({ description: "Total production of commodities" }),
  "Total disappearance": z.number().openapi({ description: "Total disappearance of commodities" }),
  "Soybean oil, for methyl ester": z.number().openapi({ description: "Soybean oil used for methyl ester" }),
  "Yield (bushel/harvested acre)": z.number().openapi({ description: "Yield in bushels per harvested acre" }),
  "Yield (pounds/harvested acre)": z.number().openapi({ description: "Yield in pounds per harvested acre" }),
}).openapi({
  title: "Attribute Histogram Response",
  description: "Response containing various attribute data metrics",
});

export type AttributeHistogramResponse = z.infer<typeof AttributeResponseSchema>;